//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultidcPodDisruptionBudget) DeepCopyInto(out *MultidcPodDisruptionBudget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultidcPodDisruptionBudget.
func (in *MultidcPodDisruptionBudget) DeepCopy() *MultidcPodDisruptionBudget {
	if in == nil {
		return nil
	}
	out := new(MultidcPodDisruptionBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultidcPodDisruptionBudget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultidcPodDisruptionBudgetList) DeepCopyInto(out *MultidcPodDisruptionBudgetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultidcPodDisruptionBudget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultidcPodDisruptionBudgetList.
func (in *MultidcPodDisruptionBudgetList) DeepCopy() *MultidcPodDisruptionBudgetList {
	if in == nil {
		return nil
	}
	out := new(MultidcPodDisruptionBudgetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultidcPodDisruptionBudgetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultidcPodDisruptionBudgetSpec) DeepCopyInto(out *MultidcPodDisruptionBudgetSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultidcPodDisruptionBudgetSpec.
func (in *MultidcPodDisruptionBudgetSpec) DeepCopy() *MultidcPodDisruptionBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(MultidcPodDisruptionBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultidcPodDisruptionBudgetStatus) DeepCopyInto(out *MultidcPodDisruptionBudgetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultidcPodDisruptionBudgetStatus.
func (in *MultidcPodDisruptionBudgetStatus) DeepCopy() *MultidcPodDisruptionBudgetStatus {
	if in == nil {
		return nil
	}
	out := new(MultidcPodDisruptionBudgetStatus)
	in.DeepCopyInto(out)
	return out
}
